### ISSUE TITLE
NSM sidecar proxies

### ISSUE THREAD

**Issue by Arsen-Uulu** [nginxinc/nginx-service-mesh#41]
Is it possible to run sidecar proxies on regular Ec2 instances and add Services on Ec2 to the mesh? 

Similar to what Istio supports currently.

**Comment by jbyers19** [comment]
No. All services must be inside the kubernetes cluster. For a scenario like this you could use [NGINX Ingress Controller](https://github.com/nginxinc/kubernetes-ingress) to configure the cluster services to communicate with the EC2 services.

**Comment by Arsen-Uulu** [comment]
Yeah, I was looking for a scenario of having a sidecar running on Ec2 and having access to the Service Registry.
Where I could route the traffic from Ec2 -> EKS(different endpoints if I wish). 

Thanks

**Comment by brianehlert** [comment]
NGINX Ingress Controller is increasingly being used as a general purpose proxy - running in K8s instead of VMs and forwarding traffic to services that run in the K8s cluster or back out of the cluster to services that might be monolithic or VMs.

That is a different use case than extending the Mesh is.  Where you might have a combination of services inside and outside the cluster that all need to participate in the same Mesh.

Can you add a bit more clarity to what exactly you are trying to do?

**Comment by sjberman** [comment]
Closing as stale.
